version: '2'

services:
  filesystemservice:
    image: attilakolya/filesystemservice_filesystemservice:latest
    ports:
     - "8080:8080"
    depends_on:
      - rabbitmq
    volumes:
      - ./FileSystemService/Storage:/FileSystemService
    environment:
     #numero di replicamanager gestiti dal dbmanager. Per aggiungere una replica basterà incrementare questo parametro
     #e aggiungere il relativo servizio in questo file seguendo la stessa convenzione (numeri nei nomi sequenziali) 
     - RABBITMQ_USERNAME=user
     - RABBITMQ_PASSWORD=bitnami
    restart: always

  dbmanager:
    image: attilakolya/filesystemservice_dbmanager:latest
    ports:
     - "43637:8080"
    environment:
     #numero di replicamanager gestiti dal dbmanager. Per aggiungere una replica basterà incrementare questo parametro
     #e aggiungere il relativo servizio in questo file seguendo la stessa convenzione (numeri nei nomi sequenziali) 
     - REPLICAS_NUMBER=5
     - RABBITMQ_USERNAME=user
     - RABBITMQ_PASSWORD=bitnami
    depends_on:
     - replicamanager_1
#     - replicamanager_2
#     - replicamanager_3
#     - replicamanager_4
#     - replicamanager_5
     - rabbitmq
    restart: always

  replicamanager_1:
    image: attilakolya/filesystemservice_replicamanager:latest
    ports: 
     - "43638:8080"
    volumes:
      - ./ReplicaManager/Replicas_volumes/Replica_1/dbData:/dbData
      - ./ReplicaManager/Replicas_volumes/Replica_1/dbLog:/dbLog
    restart: always

#  replicamanager_2:
#    build: ./ReplicaManager/
#    ports:
#     - "43639:8080"
#    volumes:
#      - ./ReplicaManager/Replicas_volumes/Replica_2/dbData:/dbData
#      - ./ReplicaManager/Replicas_volumes/Replica_2/dbLog:/dbLog
#    restart: always
#
#  replicamanager_3:
#    build: ./ReplicaManager/
#    ports:
#     - "43640:8080"
#    volumes:
#      - ./ReplicaManager/Replicas_volumes/Replica_3/dbData:/dbData
#      - ./ReplicaManager/Replicas_volumes/Replica_3/dbLog:/dbLog
#    restart: always
#
#  replicamanager_4:
#    build: ./ReplicaManager/
#    ports:
#     - "43641:8080"
#    volumes:
#      - ./ReplicaManager/Replicas_volumes/Replica_4/dbData:/dbData
#      - ./ReplicaManager/Replicas_volumes/Replica_4/dbLog:/dbLog
#    restart: always
#
#  replicamanager_5:
#    build: ./ReplicaManager/
#    ports:
#     - "43642:8080"
#    volumes:
#      - ./ReplicaManager/Replicas_volumes/Replica_5/dbData:/dbData
#      - ./ReplicaManager/Replicas_volumes/Replica_5/dbLog:/dbLog
#    restart: always

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
     - '4369:4369'
     - '5672:5672'
     - '25672:25672'
     - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'
    restart: always
volumes:
  rabbitmq_data:
    driver: local
